services:
  user-management-php:
    container_name: user-management-php
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-fpm/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      - PHP_IDE_CONFIG=serverName=full_project
    networks:
      - user.management.network

  user-management-nginx:
    container_name: user-management-nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    depends_on:
      - user-management-php
    networks:
      - user.management.network

  user-management-postgres:
    container_name: user-management-postgres
    image: postgres
    restart: always
    networks:
        - user.management.network
    environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
        - ./docker/postgres/datadir:/var/lib/postgresql/data
    ports:
        - "8432:5432"

networks:
  user.management.network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.121.0/28
